version: '3.8'
services:
  app:
    # crowdsec integrated drop in replacement for nginx proxy manager 'jc21/nginx-proxy-manager:latest'
    image: 'lepresidente/nginxproxymanager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt