version: "3.7"

networks:
  global:
    external: true
  local:
    external: false

services:
  jellyfin:
    image: jellyfin/jellyfin
    # run container as current user
    user: ${ENV_PUID}:${ENV_PGID}
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ${SERVICES_DIR}/jellyfin/config:/config
      - ${SERVICES_DIR}/jellyfin/cache:/cache
      - type: bind
        source: ${DATA_DIR}/media
        target: /media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://${SUB_DOMAIN_JELLYFIN}.${DOMAIN}
      - TZ=${TIMEZONE}
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/data/downloads
      - ${DATA_DIR}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  # downloads movies
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/radarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  # Downloads TV series
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/sonarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  # Indexer manager
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/jellyseerr:/app/config
    ports:
      - 5055:5055

  # NZB downloader
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${ENV_PUID}
      - PGID=${ENV_PGID}
      - TZ={TIMEZONE}
    volumes:
      - ${SERVICES_DIR}/transmission:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/watch:/watch
    ports:
      - 8080:8080
    restart: unless-stopped
